routes/web.php
<?php

use App\Http\Controllers\admin\{
    AuthController as AuthControllerAdmin,
    DashboardController as DashboardControllerAdmin,
    KategoriController as KategoriControllerAdmin,
    SatuanController as SatuanControllerAdmin,
    SupplierController as SupplierControllerAdmin,
    ProdukController as ProdukControllerAdmin,
    StokProdukController as StokProdukControllerAdmin,
};

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Hash;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('clear-all', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('config:cache');
    return '<h1>Cache Clear</h1>';
});


Route::get('/', function () {
    return redirect()->route('admin.login');
});
Route::get('/pass', function () {
    echo Hash::make("admin");
});


// Auth Admin
Route::get('/login-admin', [AuthControllerAdmin::class, 'index'])->name('admin.login');
Route::post('/login-admin', [AuthControllerAdmin::class, 'store'])->name('admin.login.store');

Route::middleware(['role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/logout', [AuthControllerAdmin::class, 'logout'])->name('logout');
    Route::resource('/dashboard', DashboardControllerAdmin::class);
    Route::resource('/kategori', KategoriControllerAdmin::class);
    Route::resource('/satuan', SatuanControllerAdmin::class);
    Route::resource('/supplier', SupplierControllerAdmin::class);

    //group route produk
    Route::resource('produk', ProdukControllerAdmin::class);
    Route::get('produk/editStok/{id}', [ProdukControllerAdmin::class, 'editStok'])->name('produk.editStok');
    Route::put('produk/updateStok/{id}', [ProdukControllerAdmin::class, 'updateStok'])->name('produk.updateStok');
    Route::get('produk/editStok/{stokID}/{produkID}', [ProdukControllerAdmin::class, 'editStok'])->name('produk.editStok');
    Route::get('produk/editHarga/{stokID}/{produkID}', [ProdukControllerAdmin::class, 'editHarga'])->name('produk.editHarga');
    //end route group produk

    //group route stokProduk
    Route::resource('/stokProduk', StokProdukControllerAdmin::class);
    Route::get('stokProduk/getSatuanByProdukJson/{idProduk}', [StokProdukControllerAdmin::class, 'getSatuanByProdukJson'])->name('stokProduk.getSatuanByProdukJson');
    //end route group stokProduk
});

app/Models/Satuan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Satuan extends Model
{
    use HasFactory;
    protected $table = "satuan";
    public $primaryKey = 'id_satuan';

    protected $fillable = [
        'nama', 'keterangan',
    ];

    public function stok()
    {
        return $this->hasMany(StokProduk::class, 'satuan_id');
    }
}

app/Http/Controllers/admin/SatuanController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Satuan;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class SatuanController extends Controller
{
    protected $dataView;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataView['satuan'] = Satuan::all();
        return view('admin.satuan.index', $dataView);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.satuan.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate(
            [
                'nama' => 'required|max:10|unique:satuan,nama',
                'keterangan' => 'max:25'
            ]
        );

        try {
            Log::info('Request simpan satuan = ' . json_encode($request->all()));
            Log::info("Data User = " . json_encode(auth()->guard('admin')->user()));
            Log::info('Start');

            DB::beginTransaction();
            $satuan =  Satuan::create([
                'nama' => strtoupper($request->nama),
                'keterangan' => ucfirst($request->keterangan ?? '-'),
            ]);

            Log::info("Data Satuan Baru = " . json_encode($satuan));

            DB::commit();

            return redirect()->route('admin.satuan.index')->with(['jenis' => 'success', 'pesan' => 'Berhasil menambahkan satuan']);
        } catch (\Exception $exception) {
            DB::rollBack();
            Log::error("Error simpan data satuan = " . $exception->getMessage());
            Log::error("Error simpan data satuan = " . $exception->getFile());
            Log::error("Error simpan data satuan = " . $exception->getTraceAsString());

            return redirect()->route('admin.satuan.index')->with(['jenis' => 'error', 'pesan' => 'Gagal menambahkan satuan']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dataView['satuan'] = Satuan::find($id);
        return view('admin.satuan.edit', $dataView);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $satuan = Satuan::find($id);

        $request->validate([
            'nama' => "required|max:10|unique:satuan,nama,$satuan->id_satuan,id_satuan",
            'keterangan' => 'max:25',
        ]);

        try {
            Log::info('Request update data satuan berisi = ' . json_encode($satuan));
            Log::info("Data User = " . json_encode(auth()->guard('admin')->user()));
            Log::info('Start');

            DB::beginTransaction();
            $satuan->update([
                'nama' => strtoupper($request->nama),
                'keterangan' => ucfirst($request->keterangan ?? '-'),
            ]);

            Log::info("Data satuan setelah diupdate = " . json_encode($satuan));

            DB::commit();

            return redirect()->route('admin.satuan.index')->with(['jenis' => 'success', 'pesan' => 'Berhasil update satuan']);
        } catch (\Exception $exception) {
            DB::rollBack();
            Log::error("Error update data satuan = " . $exception->getMessage());
            Log::error("Error update data satuan = " . $exception->getFile());
            Log::error("Error update data satuan = " . $exception->getTraceAsString());

            return redirect()->route('admin.satuan.index')->with(['jenis' => 'error', 'pesan' => 'Gagal update satuan']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $satuan = Satuan::find($id);
        Log::info('Request data satuan yang ingin didelete = ' . json_encode($satuan));
        Log::info("Data User = " . json_encode(auth()->guard('admin')->user()));
        Log::info('Start');

        $satuan->delete();

        Log::info('Data satuan berhasil di delete');

        return redirect()->route('admin.satuan.index')->with(['jenis' => 'success', 'pesan' => 'Berhasil delete satuan']);
    }
}

resources/views/admin/satuan/create.blade.php
@extends('layouts.app')

@section('title')
    Create Satuan
@endsection

@section('content')
    <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('admin.satuan.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Tambah Satuan Baru</h1>
    </div>

    <div class="section-body">
        <h2 class="section-title">Tambah Satuan</h2>
        <p class="section-lead">
            Halaman ini digunakan untuk menambahkan data satuan baru untuk produk.
        </p>

        <div class="row">
            <div class="col-12">
                <div class="card" id="card">
                    <div class="card-header">
                        <h4>Isikan data satuan produk baru.</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.satuan.store') }}" method="POST">
                            @csrf
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama
                                    Satuan</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama"
                                        value="{{ old('nama') }}">
                                    @error('nama')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Keterangan</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('keterangan') is-invalid @enderror"
                                        name="keterangan" value="{{ old('keterangan') }}">
                                    @error('keterangan')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                <div class="col-sm-12 col-md-7">
                                    <button class="btn btn-primary" onclick="simpan()">Tambah</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/satuan/edit.blade.php
@extends('layouts.app')

@section('title')
    Edit Satuan
@endsection

@section('content')
    <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('admin.satuan.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Edit Satuan Baru</h1>
    </div>

    <div class="section-body">
        <h2 class="section-title">Edit Satuan</h2>
        <p class="section-lead">
            Halaman ini digunakan untuk mengedit data satuan untuk produk.
        </p>

        <div class="row">
            <div class="col-12">
                <div class="card" id="card">
                    <div class="card-header">
                        <h4>Silahkan edit data satuan.</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.satuan.update', $satuan->id_satuan) }}" method="POST">
                            @csrf
                            @method('put')
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama
                                    Satuan</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama"
                                        value="{{ $satuan->nama }}">
                                    @error('nama')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Keterangan</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('keterangan') is-invalid @enderror"
                                        name="keterangan" value="{{ $satuan->keterangan }}">
                                    @error('keterangan')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                <div class="col-sm-12 col-md-7">
                                    <button class="btn btn-primary" onclick="simpan()">Simpan</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/satuan/index.blade.php
@extends('layouts.app')

@section('title')
    Satuan
@endsection

@push('css')
    <link rel="stylesheet" href="{{ asset('node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('node_modules/datatables.net-select-bs4/css/select.bootstrap4.min.css') }}">
@endpush

@section('content')
    <div class="section-header">
        <h1>Satuan Produk</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h4>Data Satuan</h4>
                        <div class="card-header-action">
                            <a href="{{ route('admin.satuan.create') }}" class="btn btn-primary">Tambah Satuan</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered tabled">
                                <thead>
                                    <tr>
                                        <th class="text-center" style="max-width: 50px">
                                            No
                                        </th>
                                        <th>Nama Satuan</th>
                                        <th>Keterangan</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($satuan as $row)
                                        <tr>
                                            <td class="text-center">{{ $loop->iteration }}</td>
                                            <td>{{ $row->nama }}</td>
                                            <td>{{ $row->keterangan }}</td>
                                            <td>
                                                <a href="{{ route('admin.satuan.edit', $row->id_satuan) }}"
                                                    class="btn btn-warning">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                                <form action="{{ route('admin.satuan.destroy', $row->id_satuan) }}"
                                                    method="POST" class="d-inline"
                                                    id="form-delete-{{ $row->id_satuan }}">
                                                    @method('delete')
                                                    @csrf
                                                    <button type="button" class="btn btn-danger"
                                                        onclick="hapus({{ $row->id_satuan }})">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('node_modules/datatables/media/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('node_modules/datatables.net-select-bs4/js/select.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.tabled').dataTable();
        })
    </script>
@endpush