routes/web.php
<?php

use App\Http\Controllers\admin\{
    AuthController as AuthControllerAdmin,
    DashboardController as DashboardControllerAdmin,
    KategoriController as KategoriControllerAdmin,
    SatuanController as SatuanControllerAdmin,
    SupplierController as SupplierControllerAdmin,
    ProdukController as ProdukControllerAdmin,
    StokProdukController as StokProdukControllerAdmin,
};

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Hash;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('clear-all', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('config:cache');
    return '<h1>Cache Clear</h1>';
});


Route::get('/', function () {
    return redirect()->route('admin.login');
});
Route::get('/pass', function () {
    echo Hash::make("admin");
});


// Auth Admin
Route::get('/login-admin', [AuthControllerAdmin::class, 'index'])->name('admin.login');
Route::post('/login-admin', [AuthControllerAdmin::class, 'store'])->name('admin.login.store');

Route::middleware(['role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/logout', [AuthControllerAdmin::class, 'logout'])->name('logout');
    Route::resource('/dashboard', DashboardControllerAdmin::class);
    Route::resource('/kategori', KategoriControllerAdmin::class);
    Route::resource('/satuan', SatuanControllerAdmin::class);
    Route::resource('/supplier', SupplierControllerAdmin::class);

    //group route produk
    Route::resource('produk', ProdukControllerAdmin::class);
    Route::get('produk/editStok/{id}', [ProdukControllerAdmin::class, 'editStok'])->name('produk.editStok');
    Route::put('produk/updateStok/{id}', [ProdukControllerAdmin::class, 'updateStok'])->name('produk.updateStok');
    Route::get('produk/editStok/{stokID}/{produkID}', [ProdukControllerAdmin::class, 'editStok'])->name('produk.editStok');
    Route::get('produk/editHarga/{stokID}/{produkID}', [ProdukControllerAdmin::class, 'editHarga'])->name('produk.editHarga');
    //end route group produk

    //group route stokProduk
    Route::resource('/stokProduk', StokProdukControllerAdmin::class);
    Route::get('stokProduk/getSatuanByProdukJson/{idProduk}', [StokProdukControllerAdmin::class, 'getSatuanByProdukJson'])->name('stokProduk.getSatuanByProdukJson');
    //end route group stokProduk
});

app/Models/Supplier.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Supplier extends Model
{
    use HasFactory;

    protected $table = 'supplier';
    public $primaryKey = 'id_supplier';
    protected $fillable = [
        'nama', 'email', 'notelp', 'alamat', 'npwp',
    ];

    public function produk()
    {
        return $this->hasMany(Produk::class);
    }
}

app/Http/Controllers/admin/SupplierController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Produk;
use App\Models\Supplier;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class SupplierController extends Controller
{
    protected $dataView;

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataView['supplier'] = Supplier::all();
        return view('admin.supplier.index', $dataView);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.supplier.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $rules = [
            [
                'nama' => 'required|max:40|unique:supplier,nama',
                'notelp' => 'max:13|unique:supplier,notelp',
                'email' => 'max:50|unique:supplier,email',
                'npwp' => 'max:30|unique:supplier,npwp',
            ]
        ];

        if ($request->email != NULL) {
            $rules['email'] = 'max:50|unique:supplier,email|email:dns';
        }

        $request->validate($rules);

        try {
            Log::info('Request simpan supplier = ' . json_encode($request->all()));
            Log::info("Data User = " . json_encode(auth()->guard('admin')->user()));
            Log::info('Start');

            DB::beginTransaction();
            $supplier =  Supplier::create([
                'nama' => strtoupper($request->nama),
                'email' => $request->email,
                'notelp' => $request->notelp,
                'npwp' => $request->npwp,
                'alamat' => $request->alamat,
            ]);

            Log::info("Data Supplier Baru = " . json_encode($supplier));

            DB::commit();

            return redirect()->route('admin.supplier.index')->with(['jenis' => 'success', 'pesan' => 'Berhasil menambahkan supplier']);
        } catch (\Exception $exception) {
            DB::rollBack();
            Log::error("Error simpan data supplier = " . $exception->getMessage());
            Log::error("Error simpan data supplier = " . $exception->getFile());
            Log::error("Error simpan data supplier = " . $exception->getTraceAsString());

            return redirect()->route('admin.supplier.index')->with(['jenis' => 'error', 'pesan' => 'Gagal menambahkan supplier']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $dataView['supplier'] = Supplier::find($id);
        $dataView['produk'] = Produk::where('supplier_id', $id)->get();
        return view('admin.supplier.show', $dataView);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dataView['supplier'] = Supplier::find($id);
        return view('admin.supplier.edit', $dataView);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $supplier = Supplier::find($id);

        $rules = [
            [
                'nama' => "required|max:40|unique:supplier,nama,$supplier->id_supplier,id_supplier",
                'notelp' => "max:13|unique:supplier,notelp,$supplier->id_supplier,id_supplier",
                'email' => "max:50|unique:supplier,email,$supplier->id_supplier,id_supplier",
                'npwp' => "max:30|unique:supplier,npwp,$supplier->id_supplier,id_supplier",
            ]
        ];

        if ($request->email != NULL) {
            $rules['email'] = "max:50|unique:supplier,email,$supplier->id_supplier,id_supplier|email:dns";
        }

        $request->validate($rules);
        try {
            Log::info('Request update data supplier berisi = ' . json_encode($supplier));
            Log::info("Data User = " . json_encode(auth()->guard('admin')->user()));
            Log::info('Start');

            DB::beginTransaction();

            $supplier->update([
                'nama' => strtoupper($request->nama),
                'notelp' => $request->keterangan,
                'email' => $request->email,
                'npwp' => $request->npwp,
            ]);

            Log::info("Data supplier setelah diupdate = " . json_encode($supplier));

            DB::commit();

            return redirect()->route('admin.supplier.index')->with(['jenis' => 'success', 'pesan' => 'Berhasil update supplier']);
        } catch (\Exception $exception) {
            DB::rollBack();
            Log::error("Error update data supplier = " . $exception->getMessage());
            Log::error("Error update data supplier = " . $exception->getFile());
            Log::error("Error update data supplier = " . $exception->getTraceAsString());

            return redirect()->route('admin.supplier.index')->with(['jenis' => 'error', 'pesan' => 'Gagal update supplier']);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $supplier = Supplier::find($id);
        Log::info('Request data supplier yang ingin didelete = ' . json_encode($supplier));
        Log::info("Data User = " . json_encode(auth()->guard('admin')->user()));
        Log::info('Start');

        $supplier->delete();

        Log::info('Data supplier berhasil di delete');

        return redirect()->route('admin.supplier.index')->with(['jenis' => 'success', 'pesan' => 'Berhasil delete supplier']);
    }
}

resources/views/admin/supplier/create.blade.php
@extends('layouts.app')

@section('title')
    Create Supplier
@endsection

@section('content')
    <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('admin.supplier.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Tambah Supplier Baru</h1>
    </div>

    <div class="section-body">
        <h2 class="section-title">Tambah Supplier</h2>
        <p class="section-lead">
            Halaman ini digunakan untuk menambahkan data supplier baru.
        </p>

        <div class="row">
            <div class="col-12">
                <div class="card" id="card">
                    <div class="card-header">
                        <h4>Isikan data supplier.</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.supplier.store') }}" method="POST">
                            @csrf
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama"
                                        value="{{ old('nama') }}">
                                    @error('nama')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Email</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="email" class="form-control @error('email') is-invalid @enderror"
                                        name="email" value="{{ old('email') }}">
                                    @error('email')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">No Telp</label>
                                <div class="col-sm-12 col-md-7 input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fas fa-phone"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control phone-number" @error('notelp') is-invalid
                                        @enderror" name="notelp" value="{{ old('notelp') }}">
                                    @error('notelp')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Alamat</label>
                                <div class="col-sm-12 col-md-7">
                                    <textarea name="alamat" cols="74" rows="9" class="@error('alamat') is-invalid @enderror"
                                        style="background-color: #fdfdff; border-color: #e4e6fc;">{{ old('alamat') }}</textarea>
                                    @error('alamat')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">NPWP</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('npwp') is-invalid @enderror" name="npwp"
                                        value="{{ old('npwp') }}">
                                    @error('npwp')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                <div class="col-sm-12 col-md-7">
                                    <button class="btn btn-primary" onclick="simpan()">Tambah</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('node_modules/cleave.js/dist/cleave.min.js') }}"></script>
    <script src="{{ asset('node_modules/cleave.js/dist/addons/cleave-phone.id.js') }}"></script>
    <script>
        var cleavePN = new Cleave('.phone-number', {
            phone: true,
            phoneRegionCode: 'id'
        });
    </script>
@endpush

resources/views/admin/supplier/edit.blade.php
@extends('layouts.app')

@section('title')
    Edit Supplier
@endsection

@section('content')
    <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('admin.supplier.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Edit Supplier Baru</h1>
    </div>

    <div class="section-body">
        <h2 class="section-title">Edit Supplier</h2>
        <p class="section-lead">
            Halaman ini digunakan untuk mengedit data supplier.
        </p>

        <div class="row">
            <div class="col-12">
                <div class="card" id="card">
                    <div class="card-header">
                        <h4>Silahkan edit data supplier.</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.supplier.update', $supplier->id_supplier) }}" method="POST">
                            @csrf
                            @method('put')
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Nama</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama"
                                        value="{{ $supplier->nama }}">
                                    @error('nama')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Email</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="email" class="form-control @error('email') is-invalid @enderror"
                                        name="email" value="{{ $supplier->email }}">
                                    @error('email')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">No Telp</label>
                                <div class="col-sm-12 col-md-7 input-group">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            <i class="fas fa-phone"></i>
                                        </div>
                                    </div>
                                    <input type="text" class="form-control phone-number" @error('notelp') is-invalid
                                        @enderror" name="notelp" value="{{ $supplier->notelp }}">
                                    @error('notelp')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">Alamat</label>
                                <div class="col-sm-12 col-md-7">
                                    <textarea name="alamat" cols="74" rows="9"
                                        style="background-color: #fdfdff; border-color: #e4e6fc;"
                                        class="@error('alamat') is-invalid @enderror">{{ $supplier->alamat }}</textarea>
                                    @error('alamat')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3">NPWP</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="text" class="form-control @error('npwp') is-invalid @enderror" name="npwp"
                                        value="{{ $supplier->npwp }}">
                                    @error('npwp')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                <div class="col-sm-12 col-md-7">
                                    <button class="btn btn-primary" onclick="simpan()">Simpan</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('node_modules/cleave.js/dist/cleave.min.js') }}"></script>
    <script src="{{ asset('node_modules/cleave.js/dist/addons/cleave-phone.id.js') }}"></script>
    <script>
        var cleavePN = new Cleave('.phone-number', {
            phone: true,
            phoneRegionCode: 'id'
        });
    </script>
@endpush

resources/views/admin/supplier/index.blade.php
@extends('layouts.app')

@section('title')
    Supplier
@endsection

@push('css')
    <link rel="stylesheet" href="{{ asset('node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('node_modules/datatables.net-select-bs4/css/select.bootstrap4.min.css') }}">
@endpush

@section('content')
    <div class="section-header">
        <h1>Supplier</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h4>Data Supplier</h4>
                        <div class="card-header-action">
                            <a href="{{ route('admin.supplier.create') }}" class="btn btn-primary">Tambah Supplier</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered tabled">
                                <thead>
                                    <tr>
                                        <th class="text-center" style="max-width: 50px">
                                            No
                                        </th>
                                        <th>Nama</th>
                                        <th>Email</th>
                                        <th>No Telp</th>
                                        <th>Alamat</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($supplier as $row)
                                        <tr>
                                            <td class="text-center">{{ $loop->iteration }}</td>
                                            <td>{{ $row->nama }}</td>
                                            <td>{{ $row->email ?? '-' }}</td>
                                            <td>{{ $row->notelp ?? '-' }}</td>
                                            <td>{{ Str::limit($row->alamat, 40) ?? '-' }}</td>
                                            <td>
                                                <a href="{{ route('admin.supplier.show', $row->id_supplier) }}"
                                                    class="btn btn-info">
                                                    <i class="fas fa-eye"></i>
                                                </a>
                                                <a href="{{ route('admin.supplier.edit', $row->id_supplier) }}"
                                                    class="btn btn-warning">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                                <form action="{{ route('admin.supplier.destroy', $row->id_supplier) }}"
                                                    method="POST" class="d-inline"
                                                    id="form-delete-{{ $row->id_supplier }}">
                                                    @method('delete')
                                                    @csrf
                                                    <button type="button" class="btn btn-danger"
                                                        onclick="hapus({{ $row->id_supplier }})">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('node_modules/datatables/media/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('node_modules/datatables.net-select-bs4/js/select.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.tabled').dataTable();
        })
    </script>
@endpush

resources/views/admin/supplier/show.blade.php
@extends('layouts.app')

@section('title')
    Detail Supplier
@endsection

@push('css')
    <style>
        table,
        th,
        td {
            border: 0px;
            border-collapse: collapse;
        }

        .needbottom {
            border-bottom: 1px solid;
            border-color: rgb(240, 231, 231);
        }

        th,
        td {
            padding: 5px;
            text-align: left;
        }

        th {
            width: 200px;
        }

    </style>

    <link rel="stylesheet" href="{{ asset('node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('node_modules/datatables.net-select-bs4/css/select.bootstrap4.min.css') }}">
@endpush

@section('content')
    <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('admin.supplier.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Detail Supplier</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-12">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h4>Detail data supplier</h4>
                    </div>
                    <div class="card-body">
                        <table class="">
                            <tr class=" needbottom">
                            <th>Nama</th>
                            <td>:</td>
                            <td>{{ $supplier->nama }}</td>
                            </tr>
                            <tr class="needbottom">
                                <th>Email</th>
                                <td>:</td>
                                <td>{{ $supplier->email }}</td>
                            </tr>
                            <tr class="needbottom">
                                <th>Nomor Telepon</th>
                                <td>:</td>
                                <td>{{ $supplier->notelp }}</td>
                            </tr>
                            <tr class="needbottom">
                                <th>Alamat</th>
                                <td>:</td>
                                <td>{{ $supplier->alamat }}</td>
                            </tr>
                            <tr>
                                <th>NPWP</th>
                                <td>:</td>
                                <td>{{ $supplier->npwp }}</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h4>Data produk</h4>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered tabled">
                                <thead>
                                    <tr>
                                        <th class="text-center" style="max-width: 50px">
                                            No
                                        </th>
                                        <th>Kode Produk</th>
                                        <th>Kategori</th>
                                        <th>Nama</th>
                                        <th>Deskripsi</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($produk as $row)
                                        <tr>
                                            <td class="text-center">{{ $loop->iteration }}</td>
                                            <td>{{ $row->kode_produk }}</td>
                                            <td>{{ $row->kategori->nama }}</td>
                                            <td>{{ $row->nama }}</td>
                                            <td>{{ $row->deskripsi }}</td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('node_modules/datatables/media/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('node_modules/datatables.net-select-bs4/js/select.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.tabled').dataTable();
        })
    </script>
@endpush