routes/web.php
<?php

use App\Http\Controllers\admin\{
    AuthController as AuthControllerAdmin,
    DashboardController as DashboardControllerAdmin,
    KategoriController as KategoriControllerAdmin,
    SatuanController as SatuanControllerAdmin,
    SupplierController as SupplierControllerAdmin,
    ProdukController as ProdukControllerAdmin,
    StokProdukController as StokProdukControllerAdmin,
};

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Hash;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('clear-all', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('config:cache');
    return '<h1>Cache Clear</h1>';
});


Route::get('/', function () {
    return redirect()->route('admin.login');
});
Route::get('/pass', function () {
    echo Hash::make("admin");
});


// Auth Admin
Route::get('/login-admin', [AuthControllerAdmin::class, 'index'])->name('admin.login');
Route::post('/login-admin', [AuthControllerAdmin::class, 'store'])->name('admin.login.store');

Route::middleware(['role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/logout', [AuthControllerAdmin::class, 'logout'])->name('logout');
    Route::resource('/dashboard', DashboardControllerAdmin::class);
    Route::resource('/kategori', KategoriControllerAdmin::class);
    Route::resource('/satuan', SatuanControllerAdmin::class);
    Route::resource('/supplier', SupplierControllerAdmin::class);

    //group route produk
    Route::resource('produk', ProdukControllerAdmin::class);
    Route::get('produk/editStok/{id}', [ProdukControllerAdmin::class, 'editStok'])->name('produk.editStok');
    Route::put('produk/updateStok/{id}', [ProdukControllerAdmin::class, 'updateStok'])->name('produk.updateStok');
    Route::get('produk/editStok/{stokID}/{produkID}', [ProdukControllerAdmin::class, 'editStok'])->name('produk.editStok');
    Route::get('produk/editHarga/{stokID}/{produkID}', [ProdukControllerAdmin::class, 'editHarga'])->name('produk.editHarga');
    //end route group produk

    //group route stokProduk
    Route::resource('/stokProduk', StokProdukControllerAdmin::class);
    Route::get('stokProduk/getSatuanByProdukJson/{idProduk}', [StokProdukControllerAdmin::class, 'getSatuanByProdukJson'])->name('stokProduk.getSatuanByProdukJson');
    //end route group stokProduk
});

resources/views/layouts/partials/footer.blade.php
<div class="footer-left">
    Copyright &copy; {{ date('Y') }} Awsen

  </div>
<div class="footer-right">
  1.0.0
</div>

resources/views/layouts/partials/navbar.blade.php
<div class="navbar-bg"></div>
<nav class="navbar navbar-expand-lg main-navbar">
    <form class="form-inline mr-auto">
        <ul class="navbar-nav mr-3">
            <li><a href="#" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
            {{-- <li><a href="#" data-toggle="search" class="nav-link nav-link-lg d-sm-none"><i class="fas fa-search"></i></a>
            </li> --}}
        </ul>
        {{-- <div class="search-element">
            <input class="form-control" type="search" placeholder="Search" aria-label="Search" data-width="250">
            <button class="btn" type="submit"><i class="fas fa-search"></i></button>
            <div class="search-backdrop"></div>
            <div class="search-result">
                <div class="search-header">
                    Histories
                </div>
                <div class="search-item">
                    <a href="#">How to hack NASA using CSS</a>
                    <a href="#" class="search-close"><i class="fas fa-times"></i></a>
                </div>
                <div class="search-item">
                    <a href="#">Kodinger.com</a>
                    <a href="#" class="search-close"><i class="fas fa-times"></i></a>
                </div>
                <div class="search-item">
                    <a href="#">#Stisla</a>
                    <a href="#" class="search-close"><i class="fas fa-times"></i></a>
                </div>
                <div class="search-header">
                    Result
                </div>
                <div class="search-item">
                    <a href="#">
                        <img class="mr-3 rounded" width="30" src="{{ asset('') }}assets/img/products/product-3-50.png"
                            alt="product">
                        oPhone S9 Limited Edition
                    </a>
                </div>
                <div class="search-item">
                    <a href="#">
                        <img class="mr-3 rounded" width="30" src="{{ asset('') }}assets/img/products/product-2-50.png"
                            alt="product">
                        Drone X2 New Gen-7
                    </a>
                </div>
                <div class="search-item">
                    <a href="#">
                        <img class="mr-3 rounded" width="30" src="{{ asset('') }}assets/img/products/product-1-50.png"
                            alt="product">
                        Headphone Blitz
                    </a>
                </div>
                <div class="search-header">
                    Projects
                </div>
                <div class="search-item">
                    <a href="#">
                        <div class="search-icon bg-danger text-white mr-3">
                            <i class="fas fa-code"></i>
                        </div>
                        Stisla Admin Template
                    </a>
                </div>
                <div class="search-item">
                    <a href="#">
                        <div class="search-icon bg-primary text-white mr-3">
                            <i class="fas fa-laptop"></i>
                        </div>
                        Create a new Homepage Design
                    </a>
                </div>
            </div>
        </div> --}}
    </form>
    <ul class="navbar-nav navbar-right">
        <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown"
                class="nav-link nav-link-lg message-toggle beep"><i class="far fa-envelope"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
                <div class="dropdown-header">Messages
                    <div class="float-right">
                        <a href="#">Mark All As Read</a>
                    </div>
                </div>
                <div class="dropdown-list-content dropdown-list-message">
                    <a href="#" class="dropdown-item dropdown-item-unread">
                        <div class="dropdown-item-avatar">
                            <img alt="image" src="{{ asset('assets/img/avatar/avatar-1.png') }}"
                                class="rounded-circle">
                            <div class="is-online"></div>
                        </div>
                        <div class="dropdown-item-desc">
                            <b>Kusnaedi</b>
                            <p>Hello, Bro!</p>
                            <div class="time">10 Hours Ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item dropdown-item-unread">
                        <div class="dropdown-item-avatar">
                            <img alt="image" src="{{ asset('assets/img/avatar/avatar-2.png') }}"
                                class="rounded-circle">
                        </div>
                        <div class="dropdown-item-desc">
                            <b>Dedik Sugiharto</b>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit</p>
                            <div class="time">12 Hours Ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item dropdown-item-unread">
                        <div class="dropdown-item-avatar">
                            <img alt="image" src="{{ asset('assets/img/avatar/avatar-3.png') }}"
                                class="rounded-circle">
                            <div class="is-online"></div>
                        </div>
                        <div class="dropdown-item-desc">
                            <b>Agung Ardiansyah</b>
                            <p>Sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                            <div class="time">12 Hours Ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="dropdown-item-avatar">
                            <img alt="image" src="{{ asset('assets/img/avatar/avatar-4.png') }}"
                                class="rounded-circle">
                        </div>
                        <div class="dropdown-item-desc">
                            <b>Ardian Rahardiansyah</b>
                            <p>Duis aute irure dolor in reprehenderit in voluptate velit ess</p>
                            <div class="time">16 Hours Ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="dropdown-item-avatar">
                            <img alt="image" src="{{ asset('assets/img/avatar/avatar-5.png') }}"
                                class="rounded-circle">
                        </div>
                        <div class="dropdown-item-desc">
                            <b>Alfa Zulkarnain</b>
                            <p>Exercitation ullamco laboris nisi ut aliquip ex ea commodo</p>
                            <div class="time">Yesterday</div>
                        </div>
                    </a>
                </div>
                <div class="dropdown-footer text-center">
                    <a href="#">View All <i class="fas fa-chevron-right"></i></a>
                </div>
            </div>
        </li>
        <li class="dropdown dropdown-list-toggle"><a href="#" data-toggle="dropdown"
                class="nav-link notification-toggle nav-link-lg beep"><i class="far fa-bell"></i></a>
            <div class="dropdown-menu dropdown-list dropdown-menu-right">
                <div class="dropdown-header">Notifications
                    <div class="float-right">
                        <a href="#">Mark All As Read</a>
                    </div>
                </div>
                <div class="dropdown-list-content dropdown-list-icons">
                    <a href="#" class="dropdown-item dropdown-item-unread">
                        <div class="dropdown-item-icon bg-primary text-white">
                            <i class="fas fa-code"></i>
                        </div>
                        <div class="dropdown-item-desc">
                            Template update is available now!
                            <div class="time text-primary">2 Min Ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="dropdown-item-icon bg-info text-white">
                            <i class="far fa-user"></i>
                        </div>
                        <div class="dropdown-item-desc">
                            <b>You</b> and <b>Dedik Sugiharto</b> are now friends
                            <div class="time">10 Hours Ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="dropdown-item-icon bg-success text-white">
                            <i class="fas fa-check"></i>
                        </div>
                        <div class="dropdown-item-desc">
                            <b>Kusnaedi</b> has moved task <b>Fix bug header</b> to <b>Done</b>
                            <div class="time">12 Hours Ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="dropdown-item-icon bg-danger text-white">
                            <i class="fas fa-exclamation-triangle"></i>
                        </div>
                        <div class="dropdown-item-desc">
                            Low disk space. Let's clean it!
                            <div class="time">17 Hours Ago</div>
                        </div>
                    </a>
                    <a href="#" class="dropdown-item">
                        <div class="dropdown-item-icon bg-info text-white">
                            <i class="fas fa-bell"></i>
                        </div>
                        <div class="dropdown-item-desc">
                            Welcome to Stisla template!
                            <div class="time">Yesterday</div>
                        </div>
                    </a>
                </div>
                <div class="dropdown-footer text-center">
                    <a href="#">View All <i class="fas fa-chevron-right"></i></a>
                </div>
            </div>
        </li>
        <li class="dropdown"><a href="#" data-toggle="dropdown"
                class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                <img alt="image" src="{{ asset('assets/img/avatar/avatar-1.png') }}" class="rounded-circle mr-1">
                <div class="d-sm-none d-lg-inline-block">Admin AWSEN</div>
            </a>
            <div class="dropdown-menu dropdown-menu-right">
                <div class="dropdown-title">Logged in 5 min ago</div>
                <a href="features-profile.html" class="dropdown-item has-icon">
                    <i class="far fa-user"></i> Profile
                </a>
                <a href="features-activities.html" class="dropdown-item has-icon">
                    <i class="fas fa-bolt"></i> Activities
                </a>
                <div class="dropdown-divider"></div>
                <a href="{{ route('admin.logout') }}" class="dropdown-item has-icon text-danger">
                    <i class="fas fa-sign-out-alt"></i> Logout
                </a>
            </div>
        </li>
    </ul>
</nav>

resources/views/layouts/partials/sidebar-menu.blade.php
<li class="menu-header">Dashboard</li>
<li class="nav-item @if (Request::is('admin/dashboard')) active @endif">
    <a href="{{ route('admin.dashboard.index') }}" class="nav-link"><i
            class="fas fa-fire"></i><span>Dashboard</span></a>
</li>
<li class="menu-header">Data Master</li>
<li class="nav-item @if (Request::is('admin/kategori')) active @endif">
    <a href="{{ route('admin.kategori.index') }}" class="nav-link"><i class="fas fa-list-alt"></i><span>Kategori
            Produk</span></a>
</li>
<li class="nav-item @if (Request::is('admin/satuan')) active @endif">
    <a href="{{ route('admin.satuan.index') }}" class="nav-link"><i
            class="fas fa-balance-scale"></i><span>Satuan</span></a>
</li>
<li class="nav-item @if (Request::is('admin/supplier')) active @endif">
    <a href="{{ route('admin.supplier.index') }}" class="nav-link"><i
            class="fas fa-building"></i><span>Supplier</span></a>
</li>
<li class="nav-item @if (Request::is('admin/produk')) active @endif">
    <a href="{{ route('admin.produk.index') }}" class="nav-link"><i
            class="fas fa-boxes"></i><span>Produk</span></a>
</li>
<li class="nav-item @if (Request::is('admin/stokProduk')) active @endif">
    <a href="{{ route('admin.stokProduk.index') }}" class="nav-link"><i class="fas fa-box"></i><span>Stok
            Produk</span></a>
</li>

<li class="menu-header">Stisla</li>
<li class="nav-item dropdown">
    <a href="#" class="nav-link has-dropdown"><i class="far fa-file-alt"></i> <span>Contekan</span></a>
    <ul class="dropdown-menu">
        <li><a class="nav-link" href="forms-advanced-form.html">Advanced Form</a></li>
        <li><a class="nav-link" href="forms-editor.html">Editor</a></li>
        <li><a class="nav-link" href="forms-validation.html">Validation</a></li>
    </ul>
</li>

resources/views/layouts/partials/sidebar.blade.php
<aside id="sidebar-wrapper">
    <div class="sidebar-brand">
        <a href="index.html">AWSEN</a>
    </div>
    <div class="sidebar-brand sidebar-brand-sm">
        <a href="index.html">AWN</a>
    </div>
    <ul class="sidebar-menu">
        @include('layouts.partials.sidebar-menu')
    </ul>
</aside>

resources/views/layouts/partials/toastMessage.blade.php
@if(Session::has('pesan'))
    @if (Session::get('jenis') == "error")
        <script>
            $(document).ready(function () {
                iziToast.error({
                    title: `Error :(`,
                    message: `{{ session('pesan') }}`,
                    position: 'topRight'
                });
            })
        </script>
    @elseif (Session::get('jenis') == "warning")
        <script>
            $(document).ready(function () {
                iziToast.warning({
                    title: 'Warning !',
                    message: `{{ session('pesan') }}`,
                    position: 'topRight'
                });
            })
        </script>
    @elseif (Session::get('jenis') == "show")
        <script>
            $(document).ready(function () {
                iziToast.show({
                    title: 'Show',
                    message: `{{ session('pesan') }}`,
                    position: 'bottomRight' 
                });
            })
        </script>
    @elseif (Session::get('jenis') == "success")
        <script>
            $(document).ready(function () {
                iziToast.success({
                    title: 'Berhasil',
                    message: `{{ session('pesan') }}`,
                    position: 'bottomRight' 
                });
            })
        </script>
    @endif
@endif