routes/web.php
<?php

use App\Http\Controllers\admin\{
    AuthController as AuthControllerAdmin,
    DashboardController as DashboardControllerAdmin,
    KategoriController as KategoriControllerAdmin,
    SatuanController as SatuanControllerAdmin,
    SupplierController as SupplierControllerAdmin,
    ProdukController as ProdukControllerAdmin,
    StokProdukController as StokProdukControllerAdmin,
};

use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Hash;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('clear-all', function () {
    Artisan::call('cache:clear');
    Artisan::call('route:clear');
    Artisan::call('view:clear');
    Artisan::call('config:cache');
    return '<h1>Cache Clear</h1>';
});


Route::get('/', function () {
    return redirect()->route('admin.login');
});
Route::get('/pass', function () {
    echo Hash::make("admin");
});


// Auth Admin
Route::get('/login-admin', [AuthControllerAdmin::class, 'index'])->name('admin.login');
Route::post('/login-admin', [AuthControllerAdmin::class, 'store'])->name('admin.login.store');

Route::middleware(['role:admin'])->prefix('admin')->name('admin.')->group(function () {
    Route::get('/logout', [AuthControllerAdmin::class, 'logout'])->name('logout');
    Route::resource('/dashboard', DashboardControllerAdmin::class);
    Route::resource('/kategori', KategoriControllerAdmin::class);
    Route::resource('/satuan', SatuanControllerAdmin::class);
    Route::resource('/supplier', SupplierControllerAdmin::class);

    //group route produk
    Route::resource('produk', ProdukControllerAdmin::class);
    Route::get('produk/editStok/{id}', [ProdukControllerAdmin::class, 'editStok'])->name('produk.editStok');
    Route::put('produk/updateStok/{id}', [ProdukControllerAdmin::class, 'updateStok'])->name('produk.updateStok');
    Route::get('produk/editStok/{stokID}/{produkID}', [ProdukControllerAdmin::class, 'editStok'])->name('produk.editStok');
    Route::get('produk/editHarga/{stokID}/{produkID}', [ProdukControllerAdmin::class, 'editHarga'])->name('produk.editHarga');
    //end route group produk

    //group route stokProduk
    Route::resource('/stokProduk', StokProdukControllerAdmin::class);
    Route::get('stokProduk/getSatuanByProdukJson/{idProduk}', [StokProdukControllerAdmin::class, 'getSatuanByProdukJson'])->name('stokProduk.getSatuanByProdukJson');
    //end route group stokProduk
});

app/Models/StokProduk.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class StokProduk extends Model
{
    use HasFactory;
    protected $table = "stokproduk";
    public $primaryKey = 'id_stokProduk';

    protected $fillable = [
        'produk_id', 'satuan_id', 'stok_barang', 'image',
    ];

    public function produk()
    {
        return $this->belongsTo(Produk::class, 'produk_id');
    }

    public function satuan()
    {
        return $this->belongsTo(Satuan::class, 'satuan_id');
    }
}

app/Http/Controllers/admin/StokProdukController.php
<?php

namespace App\Http\Controllers\admin;

use App\Http\Controllers\Controller;
use App\Models\Produk;
use App\Models\Satuan;
use App\Models\StokProduk;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;

class StokProdukController extends Controller
{
    protected $dataView;
    // $table->foreignId('produk_id');
    // $table->foreignId('satuan_id');
    // $table->bigInteger('stok_barang');
    // $table->string('image')->nullable();

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $dataView = [
            'stok' => StokProduk::get(),
        ];

        return view('admin.stokProduk.index', $dataView);
    }

    public function getSatuanByProdukJson($id_produk)
    {
        $satuan = Satuan::whereNotIn('id_satuan', function ($q) use ($id_produk) {
            $q->select('satuan_id')
                ->from(with(new StokProduk)->getTable())
                ->where('produk_id', $id_produk);
        })->get();

        return response()->json($satuan);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        // $id_produk = request('id_produk');
        // $dataView['produk'] = Produk::Find($id_produk);

        // $dataView['satuan'] = Satuan::whereNotIn('id_satuan', function ($q) use ($id_produk) {
        //     $q->select('satuan_id')
        //         ->from(with(new StokProduk)->getTable())
        //         ->where('produk_id', $id_produk);
        // })->get();
        $status = collect([
            [
                'no' => '0',
                'kondisi' => 'Bagus',
            ],
            [
                'no' => '1',
                'kondisi' => 'Expired',
            ],
            [
                'no' => '2',
                'kondisi' => 'Rusak',
            ],
        ]);

        $dataView = [
            'produk' => Produk::get(),
            'satuan' => Satuan::get(),
            'status' => $status,
        ];

        return view('admin.stokProduk.create', $dataView);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validateData = $request->validate(
            [
                'produk' => 'required',
                'image' => 'required',
                'image' => 'image|file|max:1024',
                'stok' => 'required',
                'satuan' => 'required',
                'status' => 'required',
                'harga' => 'required',
            ]
        );

        try {
            Log::info('Request simpan stok produk = ' . json_encode($request->all()));
            Log::info("Data User = " . json_encode(auth()->guard('admin')->user()));
            Log::info('Start');

            if ($request->file('image')) {
                $validateData['image'] = $request->file('image')->store('gambar-produk');
            }

            DB::beginTransaction();
            $stok =  StokProduk::create([
                'produk_id' => $validateData['produk'],
                'image' => $validateData['image'],
                'stok_barang' => $validateData['stok'],
                'satuan_id' => $validateData['satuan'],
                'status' => $validateData['status'],
            ]);

            Log::info("Data Stok Produk Baru = " . json_encode($stok));

            DB::commit();

            return redirect()->route('admin.stokProduk.index')->with(['jenis' => 'success', 'pesan' => 'Berhasil menambahkan stok produk']);
        } catch (\Exception $exception) {
            DB::rollBack();
            Log::error("Error simpan data stok produk = " . $exception->getMessage());
            Log::error("Error simpan data stok produk = " . $exception->getFile());
            Log::error("Error simpan data stok produk = " . $exception->getTraceAsString());

            return redirect()->route('admin.stokProduk.index')->with(['jenis' => 'error', 'pesan' => 'Gagal menambahkan stok produk']);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $dataView['stok'] = StokProduk::find($id);
        $dataView['satuan'] = Satuan::get();
        return view('admin.stokProduk.edit', $dataView);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(StokProduk $stokProduk)
    {
        if ($stokProduk->image) {
            Storage::delete($stokProduk->image);
        }

        Log::info('Request data stok produk yang ingin didelete = ' . json_encode($stokProduk));
        Log::info("Data User = " . json_encode(auth()->guard('admin')->user()));
        Log::info('Start');

        StokProduk::destroy($stokProduk->id_stokProduk);

        Log::info('Data stok produk berhasil di delete');

        return redirect()->route('admin.stokProduk.index')->with(['jenis' => 'success', 'pesan' => 'Berhasil Delete Stok Produk']);
    }
}

resources/views/admin/stokProduk/create.blade.php
@extends('layouts.app')

@section('title')
    Tambah Stok & Harga
@endsection

@push('css')
    <link rel="stylesheet" href="{{ asset('node_modules/select2/dist/css/select2.min.css') }}">
    <link rel="stylesheet" href="{{ asset('node_modules/selectric/public/selectric.css') }}">
@endpush

@section('content')
    <div class="section-header">
        <div class="section-header-back">
            <a href="{{ route('admin.stokProduk.index') }}" class="btn btn-icon"><i class="fas fa-arrow-left"></i></a>
        </div>
        <h1>Tambah Stok & Harga Produk</h1>
    </div>

    <div class="section-body">
        <h2 class="section-title">Tambah Stok & Harga</h2>
        <p class="section-lead">
            Halaman ini digunakan untuk menambahkan data stok dan harga baru.
        </p>

        <div class="row">
            <div class="col-12">
                <div class="card" id="card">
                    <div class="card-header">
                        <h4>Isikan data stok dan harga baru.</h4>
                    </div>
                    <div class="card-body">
                        <form action="{{ route('admin.stokProduk.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group row">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3 @error('produk_id') is-invalid @enderror">Produk</label>
                                <div class="col-sm-12 col-md-7">
                                    <select class="form-control select2" aria-label="Default select example" name="produk"
                                        id="produk" onchange="aktifkan()">
                                        <option value="false" selected disabled> --- Pilih Produk --- </option>
                                        @foreach ($produk as $p)
                                            <option value="{{ $p->id_produk }}"
                                                {{ old('produk') == $p->id_produk ? ' selected' : ' ' }}>
                                                {{ $p->nama }}</option>
                                        @endforeach
                                    </select>
                                    @error('produk_id')
                                        <div class="text-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3 @error('status') is-invalid @enderror">Status
                                    Produk</label>
                                <div class="col-sm-12 col-md-7">
                                    <select class="form-control select2" aria-label="Default select example" name="status"
                                        id="status" disabled>
                                        <option value="" selected disabled> --- Pilih Status --- </option>
                                        @foreach ($status as $st)
                                            <option value="{{ $st['no'] }}"
                                                {{ old('status') == $st['no'] ? ' selected' : ' ' }}>
                                                {{ $st['kondisi'] }}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('status')
                                        <div class="text-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label for="image"
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3 @error('image') is-invalid @enderror">Gambar
                                    Produk</label>
                                <div class="col-sm-12 col-md-7">
                                    <img class="col-sm-8 img-preview img-fluid mb-2">
                                    <div class="custom-file">
                                        <input type="file" class="custom-file-input" accept="image/*" id="image"
                                            name="image" disabled>
                                        <label class="custom-file-label" for="customFile">Choose file</label>
                                    </div>
                                    @error('image')
                                        <div class="text-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3 @error('stok') is-invalid @enderror">Stok</label>
                                <div class="col-sm-12 col-md-7">
                                    <input type="number" class="form-control @error('stok') is-invalid @enderror"
                                        name="stok" id="stok" value="{{ old('stok') }}" disabled>
                                    @error('stok')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3 @error('satuan') is-invalid @enderror">Satuan</label>
                                <div class="col-sm-12 col-md-7">
                                    <select class="form-control select2" aria-label="Default select example" name="satuan"
                                        id="satuan_id" disabled>
                                    </select>
                                    @error('satuan')
                                        <div class="text-danger">
                                            {{ $message }}
                                        </div>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label
                                    class="col-form-label text-md-right col-12 col-md-3 col-lg-3 @error('harga') is-invalid @enderror">Harga
                                    Produk</label>
                                <div class="input-group col-sm-12 col-md-7">
                                    <div class="input-group-prepend">
                                        <div class="input-group-text">
                                            IDR
                                        </div>
                                    </div>
                                    <input type="text" name="harga" value="{{ old('harga') }}"
                                        class="form-control currency" id="harga" disabled>
                                </div>
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                <div class="col-sm-12 col-md-7">
                                    @error('harga')
                                        <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-4">
                                <label class="col-form-label text-md-right col-12 col-md-3 col-lg-3"></label>
                                <div class="col-sm-12 col-md-7">
                                    <button class="btn btn-primary" id="submit" onclick="simpan()" disabled>Tambah</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('node_modules/cleave.js/dist/cleave.min.js') }}"></script>
    <script src="{{ asset('node_modules/select2/dist/js/select2.full.min.js') }}"></script>
    <script src="{{ asset('node_modules/selectric/public/jquery.selectric.min.js') }}"></script>

    <script>
        var select = document.getElementById('produk');
        var produk = select.options[select.selectedIndex].value;

        $(document).ready(function() {
            $('.select2').select2();
            var cleaveC = new Cleave('.currency', {
                numeral: true,
                numeralThousandsGroupStyle: 'thousand'
            });

            $('.custom-file-input').on('change', function() {
                let fileName = $(this).val().split('\\').pop();
                $(this).next('.custom-file-label').addClass("selected").html(fileName);
                const image = document.querySelector('#image');
                const imgPreview = document.querySelector('.img-preview');
                imgPreview.style.display = 'block';

                const ofReader = new FileReader();
                ofReader.readAsDataURL(image.files[0]);

                ofReader.onload = function(oFRevent) {
                    imgPreview.src = oFRevent.target.result;
                }
            });

            if (produk != 'false') {
                document.getElementById("status").disabled = false;
                document.getElementById("stok").disabled = false;
                document.getElementById("image").disabled = false;
                document.getElementById("satuan_id").disabled = false;
                document.getElementById("harga").disabled = false;
                document.getElementById("submit").disabled = false;
            }
        });

        function aktifkan() {
            produk = select.options[select.selectedIndex].value;

            $('#satuan_id')
                .find('option')
                .remove();

            $('#satuan_id')
                .find('option')
                .end()
                .append(`<option value="" selected disabled> --- Pilih Satuan ---</option>`)

            $.get(`{{ route('admin.stokProduk.getSatuanByProdukJson', '') }}/${produk}`, function(data) {
                $.each(data, function(index, row) {
                    $('#satuan_id')
                        .find('option')
                        .end()
                        .append(`<option value="${row.id_satuan}">${row.nama}</option>`)
                });
            });

            if (produk != 'false') {
                document.getElementById("status").disabled = false;
                document.getElementById("stok").disabled = false;
                document.getElementById("image").disabled = false;
                document.getElementById("satuan_id").disabled = false;
                document.getElementById("harga").disabled = false;
                document.getElementById("submit").disabled = false;
            }
        }
    </script>
@endpush

resources/views/admin/stokProduk/index.blade.php
@extends('layouts.app')
@section('title')
    Stok Produk
@endsection

@push('css')
    <link rel="stylesheet" href="{{ asset('node_modules/datatables.net-bs4/css/dataTables.bootstrap4.min.css') }}">
    <link rel="stylesheet" href="{{ asset('node_modules/datatables.net-select-bs4/css/select.bootstrap4.min.css') }}">
@endpush

@section('content')
    <div class="section-header">
        <h1>Stok Produk</h1>
    </div>

    <div class="section-body">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-secondary">
                    <div class="card-header">
                        <h4>Data Stok Produk</h4>
                        <div class="card-header-action">
                            <a href="{{ route('admin.stokProduk.create') }}" class="btn btn-primary">Tambah Stok Produk</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered tabled">
                                <thead>
                                    <tr>
                                        <th class="text-center" style="max-width: 50px">
                                            No
                                        </th>
                                        <th>Kode Produk</th>
                                        <th>Nama Produk</th>
                                        <th>Stok</th>
                                        <th>Satuan</th>
                                        <th>Kondisi</th>
                                        <th>Harga</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($stok as $row)
                                        <tr>
                                            <td class="text-center">{{ $loop->iteration }}</td>
                                            <td><a href="{{ route('admin.produk.show', $row->produk->id_produk) }}"
                                                    target="__blank">{{ $row->produk->kode_produk }}</a></td>
                                            <td>{{ $row->produk->nama }}</td>
                                            <td>{{ $row->stok_barang }}</td>
                                            <td>{{ $row->satuan->nama }}</td>
                                            <td>
                                                @if ($row->status == 0)
                                                    Bagus
                                                @elseif ($row->status == 1)
                                                    Expired
                                                @elseif ($row->status == 2)
                                                    Rusak
                                                @endif
                                            </td>
                                            <td></td>
                                            <td>
                                                <a href="{{ route('admin.stokProduk.show', $row->id_stokProduk) }}"
                                                    class="btn btn-info">
                                                    <i class="fas fa-eye"></i>
                                                </a>
                                                <a href="{{ route('admin.stokProduk.edit', $row->id_stokProduk) }}"
                                                    class="btn btn-warning">
                                                    <i class="fas fa-pencil-alt"></i>
                                                </a>
                                                <form
                                                    action="{{ route('admin.stokProduk.destroy', $row->id_stokProduk) }}"
                                                    method="POST" class="d-inline"
                                                    id="form-delete-{{ $row->id_stokProduk }}">
                                                    @method('delete')
                                                    @csrf
                                                    <button type="button" class="btn btn-danger"
                                                        onclick="hapus({{ $row->id_stokProduk }})">
                                                        <i class="fas fa-trash"></i>
                                                    </button>
                                                </form>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('script')
    <script src="{{ asset('node_modules/datatables/media/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js') }}"></script>
    <script src="{{ asset('node_modules/datatables.net-select-bs4/js/select.bootstrap4.min.js') }}"></script>
    <script>
        $(document).ready(function() {
            $('.tabled').dataTable();
        })
    </script>
@endpush